name: Build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: DeveloperRSquared/.github/.github/workflows/python_package_build_template.yml@main
    with:
      package_name: case_insensitive_dict

  publish_test_pypi_dry_run:
    uses: DeveloperRSquared/.github/.github/workflows/python_package_publish_template.yml@main
    needs: build
    with:
      environment: TestPyPI
      pypi_url: https://test.pypi.org/project/case-insensitive-dictionary/
      should_upload_coverage_to_codecov: true
      should_dry_run_publish_to_test_pypi: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      pypi_token: ${{ secrets.TESTPYPI_TOKEN }}
