name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_pypi:
    uses: DeveloperRSquared/.github/.github/workflows/python_package_publish_template.yml@main
    with:
      environment: PyPI
      pypi_url: https://pypi.org/project/case-insensitive-dictionary/
      should_check_package_version: true
      should_publish_to_pypi: true
      should_create_release: true
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
